### ISSUE TITLE
Criar diagrama XML das classes da aplicação.

### ISSUE THREAD

**Issue by ivmelo** [ivmelo/biblioteka#16]
Criar diagrama XML das classes da aplicação.

**Comment by pedrupawlo** [comment]
OBS: Todos os modelos tem a propriedade id (long).

![biblioteka - diagrama de classes](https://cloud.githubusercontent.com/assets/2754276/19670052/f640307e-9a42-11e6-9437-afedbb7b6630.png)

Diagramas de Classe - Done!
