### ISSUE TITLE
Correções sugeridas pelo professor - Aula 01/11/2016

### ISSUE THREAD

**Issue by pedrupawlo** [ivmelo/biblioteka#37]
- [x] Adicionar atributo "codigoDeBarras" à classe de domínio do Exemplar.
- [x] Alterar os testes configurando apenas atributos necessários para assegurar unicidade da instancia de certo dominio. i.e. Utilizar somente atributo "ISBN" na classe de testes LivrosTestes e "CPF" para a classe UsuarioTestes.

**Comment by ivmelo** [comment]
Nesse segundo box, não é pra alterar os testes. É pra alterar o @EqualsAndHashCode das classes. 

Os testes são consequência disso. :P
